In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5]) # 1D array
print(arr)
print(type(arr)) # <class 'numpy.ndarray'>
arr.dtype # dtype('int64')

[1 2 3 4 5]
<class 'numpy.ndarray'>


dtype('int64')

Data types

In [3]:
arr = np.array([1, 2, 3, 4, 5, 20.3]) # On introducing float value, all values are converted to float
arr = np.array([1, 2, 3, 4, 5, 20.3, "hii"]) # On introducing string value, all values are converted to string
arr = np.array([1, 2, 3, 4, 5, 20.3], dtype='int32') # Explicitly specifying the data type which means all values will be converted to int
print(arr)

[ 1  2  3  4  5 20]


Multiple Dimensions

In [4]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]) # 2D array
arr2.ndim # returns the number of dimensions of the array
arr2.shape # returns the shape of the array
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3D array
arr3.ndim
arr3.shape
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Indexing

In [6]:
arr = np.array([1, 2, 3, 4, 5])
arr[-4:-1] # [2, 3, 4]
arr[-2:0] # [] - empty array because the start index is greater than the end index
arr[-2:0:-1] # [4, 3, 2] - reverse the array
arr[-2:] # [4, 5]
arr[-4:-2:-1] # [] - empty array because the start index is greater than the end index
arr[2:-1:1] # [3, 4]
arr[-2:-5:-2] # [4, 2]

array([4, 2])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2 = np.array([[10,20,30,40,50], [10,20,30,40,50], [10,20,30,40,50], [10,20,30,40,50]])
arr2[-4:-1:2, -3:-1]

array([[30, 40],
       [30, 40]])

In [9]:
arr3 = np.random.randint(1, 50, (3, 5, 4)) # 3D array with random values
arr3

array([[[19,  1, 29, 14],
        [45, 24,  3, 33],
        [20, 45, 21, 12],
        [ 5, 20, 34, 49],
        [ 7, 22,  5, 45]],

       [[ 5, 25, 11, 12],
        [48, 13, 10, 20],
        [ 9, 39, 39, 43],
        [22,  2, 37, 23],
        [ 2,  5,  3, 42]],

       [[38, 29, 21, 31],
        [48, 35, 18, 34],
        [34, 32, 38, 26],
        [33,  2, 19, 30],
        [18, 45, 34, 38]]], dtype=int32)

In [10]:
# arr3[1, 2:4, 1:3]
# arr3[0:, 0, 1:3]
# arr3[:, 1:3, 1:3]
arr3[:, -4:-2, -3:-1]

array([[[24,  3],
        [45, 21]],

       [[13, 10],
        [39, 39]],

       [[35, 18],
        [32, 38]]], dtype=int32)

In [11]:
arr4 = np.random.random((2, 5, 4)) # 3D array with random float values
arr4

array([[[0.61264373, 0.58857227, 0.90335053, 0.81682367],
        [0.82350711, 0.42521335, 0.06712931, 0.71632614],
        [0.18937423, 0.9383247 , 0.3412231 , 0.66166772],
        [0.74703042, 0.97299948, 0.76632415, 0.78725829],
        [0.07056866, 0.98065511, 0.1296323 , 0.70676868]],

       [[0.96456545, 0.56164553, 0.46196203, 0.07436239],
        [0.64054999, 0.06536617, 0.71853305, 0.13012842],
        [0.79543111, 0.8565362 , 0.69291695, 0.4429782 ],
        [0.46655895, 0.20187823, 0.27682131, 0.0601596 ],
        [0.62216377, 0.2278385 , 0.4469002 , 0.25501081]]])

In [12]:
# arr4 = np.ones((2, 5, 4)) # 3D array with all values as 1
arr4 = np.zeros((2, 5, 4)) # 3D array with all values as 1
arr4.astype(int, copy=False) # copy=False will change the original array

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [13]:
arr4 = np.linspace(1, 10, 5) # 20 values between 1 and 10 with equal difference(uniform distribution)
arr4 = np.arange(1, 10, 2) # it will generate values between 1 and 10 with difference of 2 (non-uniform distribution)
arr4

array([1, 3, 5, 7, 9])

In [14]:
arr4 = np.random.randint(1, 12, 10)
arr4

array([1, 5, 5, 8, 8, 5, 1, 2, 8, 8], dtype=int32)

In [15]:
# Aggregate functions
# 1. np.sum() or arr.sum()
# 2. np.mean() or arr.mean()
# 3. np.median()
# 4. np.std() or arr.std()
# 5. np.var() or arr.var()
# 6. np.min() or arr.min()
# 7. np.max() or arr.max()
# 8. np.argmin() or arr.argmin() - returns the index of the minimum value
# 9. np.argmax() or arr.argmax() - returns the index of the maximum value
# 10. np.percentile() or 
# 11. np.any() - returns True if any of the value is True

In [16]:
np.power(2,10)
print(arr4)
print(np.cumsum(arr4)) # cumulative sum - returns an array with the sum of all the values till that index
print(np.cumprod(arr4)) # cumulative product - returns an array with the product of all the values till that index
print(np.diff(arr4)) # difference between the consecutive values

[1 5 5 8 8 5 1 2 8 8]
[ 1  6 11 19 27 32 33 35 43 51]
[      1       5      25     200    1600    8000    8000   16000  128000
 1024000]
[ 4  0  3  0 -3 -4  1  6  0]


In [17]:
arr4.sort() # by default it will sort in ascending order
arr4

array([1, 1, 2, 5, 5, 5, 8, 8, 8, 8], dtype=int32)

In [18]:
arr4[2] = 4
arr4

array([1, 1, 4, 5, 5, 5, 8, 8, 8, 8], dtype=int32)

In [19]:
arr4 = np.array([8, 7, 9, 5, 2, 3])
arr4.argmin()
arr4.argmax()
arr4.argsort() # returns the indices of the sorted array

array([4, 5, 3, 1, 0, 2])

In [20]:
arr4 = np.random.randint(1, 50, (3, 5, 4))
arr4.shape
arr4.ravel() # converts the 3D array to 1D array but it creates a view of the array which means if the original array is changed, the view will also be changed
arr4.flatten() # converts the 3D array to 1D array but it creates a copy of the array which means if the original array is changed, the copy will not be changed

array([32, 17, 30, 31,  3, 22, 20, 22,  7, 38, 41,  9, 32, 35, 36,  9, 36,
       28, 11, 20, 26, 34,  9, 32, 37, 22, 49, 45, 49,  8, 36, 15, 26,  7,
       10, 13, 10, 29,  8, 46, 19, 48,  5, 23, 30,  2,  5, 49, 22, 44, 13,
       27, 21, 39, 23,  6,  5, 39, 24, 48], dtype=int32)

In [21]:
arr4.size # returns the total number of elements in the array
arr4.itemsize # returns the size of each element in the array
arr4.nbytes # returns the total number of bytes occupied by the array
arr4.reshape(60) # reshapes the array to 1D array
arr4.reshape(10, 6) # reshapes the array to 2D array but it creates a copy of the array which means if the original array is changed, the copy will not be changed
arr4.resize(10, 6) # reshapes the array to 2D array but it changes the original array

In [22]:
# Transpose of an array
arr4 = np.random.randint(1, 50, (5, 3))
arr4

array([[ 4, 33, 40],
       [30,  2, 41],
       [22,  4, 23],
       [42, 36,  6],
       [ 8, 12,  6]], dtype=int32)

In [23]:
np.transpose(arr4) # returns the transpose of the array, creates copy of the array
arr4.T # returns the transpose of the array, changes original array

array([[ 4, 30, 22, 42,  8],
       [33,  2,  4, 36, 12],
       [40, 41, 23,  6,  6]], dtype=int32)

In [24]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
print(arr1)
print(arr2)
print(arr1 + arr2) # element wise addition and same for subtraction, multiplication and division

[10 20 30 40]
[1 2 3 4]
[11 22 33 44]


In [25]:
# combining arrays
np.concatenate((arr1, arr2)) # combines the arrays along the axis 0 but it creates a copy of the array, for permanent changes use axis=1
# np.vstack((arr1, arr2)) # vertically stacks the arrays
# np.hstack((arr1, arr2)) # horizontally stacks the arrays

array([10, 20, 30, 40,  1,  2,  3,  4])

In [36]:
arr1 = np.random.randint(1, 20, (5, 4))
arr2 = np.random.randint(1, 20, (5, 1))
print(arr1)
print()
print(arr2)

[[10 19 17 14]
 [19 13  8 16]
 [14 10 17 14]
 [ 8  1  3 13]
 [ 4 16 12  7]]

[[11]
 [ 7]
 [ 5]
 [ 7]
 [ 1]]


In [39]:
np.concatenate((arr1,arr2), axis=1) # axis= 1 is columnwise

array([[10, 19, 17, 14, 11],
       [19, 13,  8, 16,  7],
       [14, 10, 17, 14,  5],
       [ 8,  1,  3, 13,  7],
       [ 4, 16, 12,  7,  1]], dtype=int32)

In [46]:
arr1 = np.random.randint(1, 20, (5, 4))
arr2 = np.random.randint(1, 20, (4, 1))
print(arr1)
print()
print(arr2)

[[ 7 10  9 19]
 [ 2 12 15 10]
 [13  1 12  7]
 [10 14 13 17]
 [ 4  2 16  2]]

[[10]
 [ 3]
 [ 3]
 [15]]


In [47]:
np.concatenate((arr1,arr2.T)) # by defualt axis= 0 for rowise

array([[ 7, 10,  9, 19],
       [ 2, 12, 15, 10],
       [13,  1, 12,  7],
       [10, 14, 13, 17],
       [ 4,  2, 16,  2],
       [10,  3,  3, 15]], dtype=int32)

Matrix Operations

In [26]:
arr4 = np.random.randint(1, 12, 11)

In [27]:
print(arr4)
print(arr4 + 2)
print(arr4 * 2)

[ 9  7  1  6  9 11 10  8  9  8  5]
[11  9  3  8 11 13 12 10 11 10  7]
[18 14  2 12 18 22 20 16 18 16 10]


In [28]:
arr1 = np.random.randint(1, 200, 200)
arr1

array([ 30, 192,  34, 126, 130, 176,  89,  87, 128,  14,  51,  54,  77,
       178, 170, 165, 107,  60, 142, 176, 137, 160,  11, 114, 145,  44,
        25, 105, 198,  70, 132,  15, 116,  32,  56, 105, 173, 179, 161,
       132, 167, 161, 115, 162, 106, 175,  82,  19,  21,  13,  49,  55,
       153, 111,  72, 144,  92,  48,  16,  18, 153,  70,  65,  43,  91,
       136,  22,   4, 156,  40, 193, 127,  55, 174,  14, 157,  58,  20,
        66, 188, 189, 111, 128, 127,  82, 109,  14, 148,   5, 192, 142,
        88, 178, 118, 179,  40, 173, 165,  50, 156,  29,   3,  86, 150,
        92, 190, 132, 172, 144, 158, 144,  68,  49,  80,   6, 130, 113,
        19,  82,  81, 153,  67, 131,  25, 160,  57,  19, 166,  30,  37,
       139, 157, 193,  36, 182, 170,   1, 169,  41, 129, 161, 104,  85,
        87,  70,  75, 158, 163, 176,  91, 183, 157, 177,  78, 119,  95,
        86, 160, 136,  94,  40,  52,  52,  97,   6, 154, 109, 137,  30,
       155, 172, 145,  72,  10, 184, 118, 169,  40, 123, 138, 17

In [29]:
temp = []
for item in arr1:
    if item < 100:
        temp.append(item)

print(temp)
print(len(temp))

[np.int32(30), np.int32(34), np.int32(89), np.int32(87), np.int32(14), np.int32(51), np.int32(54), np.int32(77), np.int32(60), np.int32(11), np.int32(44), np.int32(25), np.int32(70), np.int32(15), np.int32(32), np.int32(56), np.int32(82), np.int32(19), np.int32(21), np.int32(13), np.int32(49), np.int32(55), np.int32(72), np.int32(92), np.int32(48), np.int32(16), np.int32(18), np.int32(70), np.int32(65), np.int32(43), np.int32(91), np.int32(22), np.int32(4), np.int32(40), np.int32(55), np.int32(14), np.int32(58), np.int32(20), np.int32(66), np.int32(82), np.int32(14), np.int32(5), np.int32(88), np.int32(40), np.int32(50), np.int32(29), np.int32(3), np.int32(86), np.int32(92), np.int32(68), np.int32(49), np.int32(80), np.int32(6), np.int32(19), np.int32(82), np.int32(81), np.int32(67), np.int32(25), np.int32(57), np.int32(19), np.int32(30), np.int32(37), np.int32(36), np.int32(1), np.int32(41), np.int32(85), np.int32(87), np.int32(70), np.int32(75), np.int32(91), np.int32(78), np.int32(9

In [31]:
arr1[arr1 < 100] # returns the values less than 100

array([30, 34, 89, 87, 14, 51, 54, 77, 60, 11, 44, 25, 70, 15, 32, 56, 82,
       19, 21, 13, 49, 55, 72, 92, 48, 16, 18, 70, 65, 43, 91, 22,  4, 40,
       55, 14, 58, 20, 66, 82, 14,  5, 88, 40, 50, 29,  3, 86, 92, 68, 49,
       80,  6, 19, 82, 81, 67, 25, 57, 19, 30, 37, 36,  1, 41, 85, 87, 70,
       75, 91, 78, 95, 86, 94, 40, 52, 52, 97,  6, 30, 72, 10, 40, 41, 19,
       25, 19,  5,  9, 32, 86, 82,  9], dtype=int32)

In [32]:
arr = np.random.randint(1, 40, 20)
np.where(arr < 20, 0, 1) # if the value is less than 20, replace it with 0 else replace it with 1

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [33]:
arr1 = np.random.randint(1, 20, 5)
arr2 = np.random.randint

array([28, 10,  2, 18,  5, 24, 33, 26, 11,  5, 22, 23, 16, 38, 11, 11, 10,
       25, 31, 39], dtype=int32)